services:
  vprodb:
    build: 
      context: ./Docker-files/db
    image: vprofile-business-register-db-image
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
  vprocache01:
    build:
      context: ./Docker-files/mc
    image: vprofile-business-register-mc-image
    container_name: vprocache01
    ports:
      - "11211:11211"
  vpromq01:
    build:
      context: ./Docker-files/mq
    image: vprofile-business-register-mq-image
    ports:
      - "5672:5672"
    environment: 
      - RABBITMQ_DEFAULT_USER=guest
      - RABBIT_MQ_PASS=guest
  vproapp:
      build: 
        context: ./Docker-files/app
      image: vprofile-business-register-app-image
      container_name: vproapp
      ports:
        - "8080:8080"
      volumes:
        - vproappdata:/usr/local/tomcat/webapps
  vproweb:
      build: 
        context: ./Docker-files/web
      image: vprofile-business-register-web-image
      container_name: vproweb
      ports:
        - "80:80"
volumes:
  vprodbdata: {}
  vproappdata: {}