apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: vprofile
    environment: dev
  annotations:
    description: "This is a test creation for vprofile app to store Mysql DB and RabbitMQ service passwords as secrets"
    kubernetes.io/service-account.name: vprofile
    kubernetes.io/created-by: darosa87
type: Opaque
data:
  db-pass: dnByb2RicGFzcw== 
  rmq-pass: Z3Vlc3Q=
